### ISSUE TITLE
[New Snap] Aptos by Solflare

### ISSUE THREAD

**Issue by kenhkan** [MetaMask/snaps-registry#115]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket?
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/@rise-wallet/aptos-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://github.com/MetaMask/snaps-registry/issues/115#issuecomment-1710937679
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue? 
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue?
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue?
- [x] The corresponding pull request in this repo has been merged. https://github.com/MetaMask/snaps-registry/pull/76

**Comment by kenhkan** [comment]
Audit report: [https___s3-us-west-2.amazonaws.com_secure.notion-static.com_756f8728-8620-4dae-931c-f2d77192a530_solflare-wallet-snaps-audit-2023-08 (1).pdf](https://github.com/MetaMask/snaps-registry/files/12554484/https___s3-us-west-2.amazonaws.com_secure.notion-static.com_756f8728-8620-4dae-931c-f2d77192a530_solflare-wallet-snaps-audit-2023-08.1.pdf)

**Comment by Montoya** [comment]
The following findings apply to the combined 3 snaps: 

- [sollare‑snap@792fcb2a253c572677271044ece061daae81ce41](https://github.com/solflare-wallet/solflare-snap/tree/792fcb2a253c572677271044ece061daae81ce41)
- [sui‑snap@39740383fd11174a406a1a27e15c92f277d00779](https://github.com/solflare-wallet/sui-snap/tree/39740383fd11174a406a1a27e15c92f277d00779)
- [aptos‑snap@36145bb8f4963eb02cff26a549ac348a34d8cb3](https://github.com/solflare-wallet/aptos-snap/tree/36145fbb8f4963eb02cff26a549ac348a34d8cb3)

List of findings: 

### 4.1 Dapp May Force a Sign Approval Dialog Without Showing the Message to Be Signed _Major_

Fixed in: https://github.com/solflare-wallet/aptos-snap/commit/b857c16b873c730a38a6762a8c6f28b7b6c73c14

### 4.2 CtrlChar/Markdown Injection in renderSignTransaction , renderSignAllTransactions _Major_

See above commit

### 4.3 Insufficient Input Validation deriveKeyPair() _Medium_

Fixed in https://github.com/solflare-wallet/aptos-snap/commit/46c4fa04e5f3c8821f85a2d5155509f50378800d

### 4.4 Dapp May Suppress User Confirmation on Request to Extract Pubkey; May Extract Any Net‑Key _Medium_

This is intentional by design. 

### 4.5 Production Builds Allow Development and Localhost Origins; Snap Does Not Enforce Transport Security _Medium_

Since the Snap now requires confirmation for any signing, the risk of this issue is lower. 

The rest of the issues cited in the audit report are minor and not required to be fixed. 

- 4.6 Misleading HTML Entity and Function Name getPrivkey
- 4.7 Use of Outdated snap.config.json Instead of snap.config.js 
- 4.8 Inconsistent or Blank Fields in package.json 
- 4.9 Consider Using @metamask/detect‑provider
- 4.10 Consider Preixing RPC Calls With solana_* , sui_* , aptos_*
- 4.11 Consider Moving to TypeScript

**Comment by Montoya** [comment]
Repository: https://github.com/solflare-wallet/aptos-snap
