### ISSUE TITLE
Secure allow-list against Man-In-The-Middle attacks

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-registry#14]
The allow list will be downloaded through some kind of proxy or CDN because GitHub doesn't allow using their repositories are production sites.

We need to ensure that the proxy can't modify the integrity of allow-list in any way.

One possibility would be to use the signing key of the extension to sign the registry as well.

### Outcome
* Research and decide on the solution to the MITM
* Implement the solution in the snap-registry and the extension

**Comment by weizman** [comment]
Some thoughts:
* Inherently, there's not much you can do if you don't trust your CDN. I tried to think about this problem for a day or two and wasn't able to think of a clever yet simple enough solution that will eliminate concern when the CDN is non trust worthy.
* In other words, I think we should focus our efforts on deciding on a CDN we can trust.
* Question: you say GitHub aren't into making their repo production sites, do you also mean GitHub Pages? Because it seems there are a lot of different initiatives out there that are using GitHub Pages as a production solution (I personally serve Google Ads on my GitHub Pages personal blog post).
* One security layer I can think of implementing to enhance security here is maybe instead of serving the list as a file, we can serve it as a cross origin iframe that loads the list inside a nonce-protected script tag:

```html
<!-- iframe (//metamask.io/list.html) -->
<script nonce="sha256-9crUEvsTwd2QD/Zjdx3vtmqkaL9G4LUOmY7WaqD/9CA=">
top.postMessage({list: <LIST>}, '<DOMAIN>');
</script>
```

```html
<!-- top (//chrome-extension/home.html) -->
<script>
onmessage(e => e.origin === 'metamask.io' && handleList(harden(JSON.parse(e.data.list))));
</script>
```

* This honestly isn't amazing because if someone can change the list, it means they can change the nonce as well (again, if you don't trust the CDN then you're screwed), but it offers some extra layer of protection.
* We can also consider uploading them (list and nonce) to different CDNs thus forcing an attacker breach 2 CDNs rather than just one?
* In addition, we can create an alert system that notifies us every time the content of the list changes by polling on the resource every X hours, so we will expect such an alert only when we update the list ourselves and we can act on alerts we weren't expecting

Just thinking out load, let's further explore this.

**Comment by kenhkan** [comment]
This is a duplicate of https://app.zenhub.com/workspaces/snaps-615b3a7c08d2b20015eb6c4e/issues/gh/metamask/snaps-registry/13. Please continue the conversations/tracking there.
