### ISSUE TITLE
[Update Snap] Cardano Wallet

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-registry#707]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the summary of the change documented in this ticket?
- [x] Has a MetaMask Snaps team member reviewed whether the changes need to be vetted?
- [x] If there are changes that need to be vetted, attach a description and the relevant fixes/remediations to this issue.
- [ ] The corresponding pull request in this repo has been merged.

**Comment by mario-christopher** [comment]
**Change Summary:**
We wanted to enhance the user's security, so we made transaction details visible directly in Metamask. The new version of the snap parses the raw transactions in order to display the user details about what the transaction does. We do that by decoding the encoded raw transaction and using cardano-sdk lib to parse the fields of the transaction in to readable form. We then display the results of the parsing on the signing screen.

**Source Diff:**
https://github.com/nufi-official/nufi-snap/compare/0.1.0...0.2.0

**Version to be allowListed:**
0.2.0
